// <auto-generated />
using System;
using IndividualProject_School.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndividualProject_School.Migrations
{
    [DbContext(typeof(IndividuelltProjektEgzonContext))]
    [Migration("20250205151802_MatchaDBs")]
    partial class MatchaDBs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndividualProject_School.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927C0589B3B4C");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateOnly>("EmploymentDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<int?>("Salary")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04F11A2000235");

                    b.HasIndex("ProfessionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<DateOnly>("DateAssigned")
                        .HasColumnType("date");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Grade1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Grade");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("GradeId")
                        .HasName("PK__Grades__54F87A573B11CE4D");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Profession", b =>
                {
                    b.Property<int>("ProfessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfessionId"));

                    b.Property<string>("ProfessionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProfessionId")
                        .HasName("PK__Professi__3F309E3F7F578913");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ssn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SSN");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__32C52B99FE236F96");

                    b.HasIndex("ClassId");

                    b.HasIndex(new[] { "Ssn" }, "UQ__Students__CA1E8E3C61824601")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subjects__AC1BA3A8CEE79803");

                    b.HasIndex("ClassId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Class", b =>
                {
                    b.HasOne("IndividualProject_School.Models.Employee", "Employee")
                        .WithMany("Classes")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK__Classes__Employe__3D5E1FD2");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Employee", b =>
                {
                    b.HasOne("IndividualProject_School.Models.Profession", "Profession")
                        .WithMany("Employees")
                        .HasForeignKey("ProfessionId")
                        .HasConstraintName("FK__Employees__Profe__398D8EEE");

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Grade", b =>
                {
                    b.HasOne("IndividualProject_School.Models.Employee", "Employee")
                        .WithMany("Grades")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK__Grades__Employee__49C3F6B7");

                    b.HasOne("IndividualProject_School.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Grades__StudentI__47DBAE45");

                    b.HasOne("IndividualProject_School.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__Grades__SubjectI__48CFD27E");

                    b.Navigation("Employee");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Student", b =>
                {
                    b.HasOne("IndividualProject_School.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__Students__ClassI__412EB0B6");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Subject", b =>
                {
                    b.HasOne("IndividualProject_School.Models.Class", "Class")
                        .WithMany("Subjects")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__Subjects__ClassI__44FF419A");

                    b.HasOne("IndividualProject_School.Models.Employee", "Employee")
                        .WithMany("Subjects")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK__Subjects__Employ__440B1D61");

                    b.Navigation("Class");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Class", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Employee", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Grades");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Profession", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("IndividualProject_School.Models.Subject", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
